### ISSUE TITLE
OverflowError on Windows when running `stencila.run()`

### ISSUE THREAD

**Issue by cuibonobo** [stencila/py#14]
Python 3.6 running on Windows 10. Running `"C:\Program Files\Python36\python.exe" -c "import stencila; stencila.run(echo=True)"` produces the following stack trace:

```txt
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\jgarcia\AppData\Roaming\Python\Python36\site-packages\stencila\__init__.py", line 35, in run
    host.run(*args, **kwargs)
  File "C:\Users\jgarcia\AppData\Roaming\Python\Python36\site-packages\stencila\host.py", line 285, in run
    time.sleep(0x7FFFFFFF)
OverflowError: sleep length is too large
```

Indeed, changing the argument of `time.sleep()` to `0x7FFFF` (chosen arbitrarily -- I deleted `F`s one-by-one until it worked) allows `run()` method to run as expected.

I'm very confused by this because the [Python 3 docs](https://docs.python.org/3/library/time.html) only mention `OverflowError` in the context of an integer overflow, which *should* be 2<sup>32</sup>. Instead, the limit here seems to be 2<sup>20</sup>.

**Comment by nokome** [comment]
Thanks for this :bug: report, very useful. I've changed the value to 1000. Since this is in a while
loop, the value can be arbitrarily high - just enough to not cause too much CPU load.
